import { PageSection } from "@/components/PageSection";
import { PageHeader, type PageLayoutProps } from "./_shared";
import { StandardPage } from "./StandardPage";
import { TestimonialsIndexPage } from "./TestimonialsIndexPage";

type FrontendNativePageProps = PageLayoutProps & {
  testimonialsPage?: number;
};

export function FrontendNativePage({ page, testimonialsPage = 1 }: FrontendNativePageProps) {
  if (page.layoutVariant === "search-results") {
    return (
      <PageSection>
        <PageHeader page={page} kicker="search" />
        <p>
          Search results are rendered by the Next.js frontend and do not depend on migrated Strapi
          body content.
        </p>
      </PageSection>
    );
  }

  if (page.layoutVariant === "sitemap") {
    return (
      <PageSection>
        <PageHeader page={page} kicker="sitemap" />
        <p>
          The XML sitemap is generated by Next.js at <a href="/sitemap.xml">/sitemap.xml</a>.
        </p>
      </PageSection>
    );
  }

  if (page.layoutVariant === "testimonials-index") {
    return <TestimonialsIndexPage page={page} currentPage={testimonialsPage} />;
  }

  return <StandardPage page={page} />;
}
