#!/usr/bin/env python3
"""Build ``babel_normalization.json`` from the deterministic audit + human reviews.

The final Strapi importer reads this single artifact instead of parsing the
unreliable MODX ``babelLanguageLinks`` TV. Inputs:

  - ``locale_pair_audit.json`` (generated by ``audit_locale_pairs.py``) is the
    ground truth for strict pairs, auto-linkable pairs, and the per-side
    ``truly_unlocalized`` buckets.
  - ``reviews.yaml`` encodes the human decisions for the ``review`` bucket and
    the cross-collision ambiguities.
  - ``transformed_resources.json`` is the coverage reference: every web id and
    every rus id must end up in exactly one bucket (pair or singleton).

The builder fails loud if the invariants below cannot be satisfied, because
silent drift here would corrupt every downstream locale link in Strapi.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from cms_audit import CHECKPOINT_SOURCE_DIR, MANIFESTS_DIR, MODX_SOURCE_DIR, REPORTS_DIR, ROOT
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
AUDIT_PATH = MANIFESTS_DIR / "locale_pair_audit.json"
REVIEWS_PATH = MANIFESTS_DIR / "reviews.yaml"
RESOURCES_PATH = MODX_SOURCE_DIR / "transformed_resources.json"
OUTPUT_PATH = MANIFESTS_DIR / "babel_normalization.json"

VALID_SINGLETON_ACTIONS = {"standalone", "skip"}


@dataclass(frozen=True)
class ResourceIndex:
    """Flat views of every row in ``transformed_resources.json``."""

    web_ids: frozenset[int]
    rus_ids: frozenset[int]


def load_json(path: Path) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except FileNotFoundError:
        raise SystemExit(f"[fatal] missing input: {path}")
    except json.JSONDecodeError as error:
        raise SystemExit(f"[fatal] invalid JSON in {path}: {error}")


def load_yaml(path: Path) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return yaml.safe_load(handle)
    except FileNotFoundError:
        raise SystemExit(f"[fatal] missing reviews file: {path}")
    except yaml.YAMLError as error:
        raise SystemExit(f"[fatal] invalid YAML in {path}: {error}")


def build_resource_index(resources_root: Any) -> ResourceIndex:
    """Flatten the nested resource tree and split ids by locale."""
    flat: list[dict[str, Any]] = []

    def walk(nodes: list[dict[str, Any]]) -> None:
        for node in nodes:
            flat.append(node)
            walk(node.get("children", []) or [])

    if isinstance(resources_root, list):
        walk(resources_root)
    elif isinstance(resources_root, dict):
        walk([resources_root])
    else:
        raise SystemExit("[fatal] transformed_resources.json has unexpected shape")

    web_ids: set[int] = set()
    rus_ids: set[int] = set()
    for node in flat:
        context = node.get("context_key")
        node_id = node.get("id")
        if not isinstance(node_id, int):
            continue
        if context == "web":
            web_ids.add(node_id)
        elif context == "rus":
            rus_ids.add(node_id)

    if not web_ids or not rus_ids:
        raise SystemExit("[fatal] resource index is empty for one or both locales")

    return ResourceIndex(web_ids=frozenset(web_ids), rus_ids=frozenset(rus_ids))


def extract_proposals(
    proposals: list[dict[str, Any]],
    bucket: str,
) -> list[dict[str, Any]]:
    return [entry for entry in proposals if entry.get("bucket") == bucket]


def first_candidate_id(entry: dict[str, Any]) -> int | None:
    candidates = entry.get("candidates") or []
    if not candidates:
        return None
    return candidates[0].get("candidate_id")


def first_candidate_reason(entry: dict[str, Any]) -> str:
    candidates = entry.get("candidates") or []
    if not candidates:
        return ""
    reasons = candidates[0].get("reasons") or []
    return "; ".join(reasons)


def validate_reviews_shape(reviews: Any) -> dict[str, Any]:
    if not isinstance(reviews, dict):
        raise SystemExit("[fatal] reviews.yaml must be a mapping at the top level")

    pairs = reviews.get("pairs") or []
    web_singletons = reviews.get("web_singletons") or []
    rus_singletons = reviews.get("rus_singletons") or []

    for label, value in (
        ("pairs", pairs),
        ("web_singletons", web_singletons),
        ("rus_singletons", rus_singletons),
    ):
        if not isinstance(value, list):
            raise SystemExit(f"[fatal] reviews.{label} must be a list")

    return {
        "pairs": pairs,
        "web_singletons": web_singletons,
        "rus_singletons": rus_singletons,
    }


def collect_audit_buckets(audit: dict[str, Any]) -> dict[str, Any]:
    strict_pairs = audit.get("strict_pairs") or []
    web_proposals = audit.get("web_proposals") or []
    rus_proposals = audit.get("rus_proposals") or []
    broken_web = audit.get("broken_web") or []
    broken_rus = audit.get("broken_rus") or []

    web_auto = extract_proposals(web_proposals, "auto_link")
    rus_auto = extract_proposals(rus_proposals, "auto_link")
    web_review = extract_proposals(web_proposals, "review")
    rus_review = extract_proposals(rus_proposals, "review")
    web_unlocalized = extract_proposals(web_proposals, "truly_unlocalized")
    rus_unlocalized = extract_proposals(rus_proposals, "truly_unlocalized")

    return {
        "strict_pairs": strict_pairs,
        "web_auto": web_auto,
        "rus_auto": rus_auto,
        "web_review": web_review,
        "rus_review": rus_review,
        "web_unlocalized": web_unlocalized,
        "rus_unlocalized": rus_unlocalized,
        "broken_web": broken_web,
        "broken_rus": broken_rus,
    }


def build_auto_pairs(
    web_auto: list[dict[str, Any]],
    rus_auto: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Auto-linkable entries reciprocate top-1; emit each reciprocal link once."""
    web_top: dict[int, int] = {}
    for entry in web_auto:
        partner = first_candidate_id(entry)
        if partner is not None:
            web_top[entry["source_id"]] = partner

    rus_top: dict[int, int] = {}
    for entry in rus_auto:
        partner = first_candidate_id(entry)
        if partner is not None:
            rus_top[entry["source_id"]] = partner

    auto_pairs: list[dict[str, Any]] = []
    emitted: set[tuple[int, int]] = set()

    for web_id, rus_id in web_top.items():
        if rus_top.get(rus_id) != web_id:
            raise SystemExit(
                f"[fatal] web {web_id} marked auto but rus {rus_id} does not reciprocate"
            )
        key = (web_id, rus_id)
        if key in emitted:
            continue
        emitted.add(key)
        reason = first_candidate_reason(
            next(entry for entry in web_auto if entry["source_id"] == web_id)
        )
        auto_pairs.append(
            {
                "web_id": web_id,
                "rus_id": rus_id,
                "source": "auto",
                "reason": reason,
            }
        )

    for rus_id, web_id in rus_top.items():
        key = (web_id, rus_id)
        if key in emitted:
            continue
        if web_top.get(web_id) != rus_id:
            raise SystemExit(
                f"[fatal] rus {rus_id} marked auto but web {web_id} does not reciprocate"
            )
        emitted.add(key)
        reason = first_candidate_reason(
            next(entry for entry in rus_auto if entry["source_id"] == rus_id)
        )
        auto_pairs.append(
            {
                "web_id": web_id,
                "rus_id": rus_id,
                "source": "auto",
                "reason": reason,
            }
        )

    return auto_pairs


def build_manual_pairs(
    review_pairs: list[dict[str, Any]],
    web_review: list[dict[str, Any]],
    rus_review: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    web_review_by_id = {entry["source_id"]: entry for entry in web_review}
    rus_review_by_id = {entry["source_id"]: entry for entry in rus_review}

    manual_pairs: list[dict[str, Any]] = []
    for index, raw in enumerate(review_pairs):
        if not isinstance(raw, dict):
            raise SystemExit(f"[fatal] reviews.pairs[{index}] is not a mapping")
        web_id = raw.get("web")
        rus_id = raw.get("rus")
        if not isinstance(web_id, int) or not isinstance(rus_id, int):
            raise SystemExit(
                f"[fatal] reviews.pairs[{index}] needs integer `web` and `rus`"
            )
        reason = str(raw.get("reason") or "").strip()
        override_info: dict[str, Any] = {}

        web_entry = web_review_by_id.get(web_id)
        audit_partner_for_web = first_candidate_id(web_entry) if web_entry else None
        if audit_partner_for_web is not None and audit_partner_for_web != rus_id:
            override_info["audit_top_1_rus"] = audit_partner_for_web

        rus_entry = rus_review_by_id.get(rus_id)
        audit_partner_for_rus = first_candidate_id(rus_entry) if rus_entry else None
        if audit_partner_for_rus is not None and audit_partner_for_rus != web_id:
            override_info["audit_top_1_web"] = audit_partner_for_rus

        entry: dict[str, Any] = {
            "web_id": web_id,
            "rus_id": rus_id,
            "source": "manual",
        }
        if reason:
            entry["reason"] = reason
        if override_info:
            entry["overrides"] = override_info
        manual_pairs.append(entry)

    return manual_pairs


def build_singletons(
    review_singletons: list[dict[str, Any]],
    audit_unlocalized: list[dict[str, Any]],
    locale_label: str,
) -> list[dict[str, Any]]:
    review_by_id: dict[int, dict[str, Any]] = {}
    for index, raw in enumerate(review_singletons):
        if not isinstance(raw, dict):
            raise SystemExit(
                f"[fatal] reviews.{locale_label}_singletons[{index}] is not a mapping"
            )
        node_id = raw.get("id")
        action = raw.get("action")
        if not isinstance(node_id, int):
            raise SystemExit(
                f"[fatal] reviews.{locale_label}_singletons[{index}] needs integer `id`"
            )
        if action not in VALID_SINGLETON_ACTIONS:
            raise SystemExit(
                f"[fatal] reviews.{locale_label}_singletons[{index}] action must be one of "
                f"{sorted(VALID_SINGLETON_ACTIONS)}"
            )
        reason = str(raw.get("reason") or "").strip()
        review_by_id[node_id] = {
            "id": node_id,
            "action": action,
            "reason": reason or "manual review",
        }

    singletons: list[dict[str, Any]] = []
    seen: set[int] = set()

    for entry in audit_unlocalized:
        node_id = entry.get("source_id")
        if not isinstance(node_id, int):
            continue
        if node_id in seen:
            continue
        seen.add(node_id)
        singletons.append(
            {
                "id": node_id,
                "action": "standalone",
                "reason": "truly_unlocalized",
            }
        )

    for node_id, payload in review_by_id.items():
        if node_id in seen:
            raise SystemExit(
                f"[fatal] {locale_label} singleton {node_id} already comes from the audit "
                f"truly_unlocalized bucket; remove it from reviews.yaml"
            )
        seen.add(node_id)
        singletons.append(payload)

    singletons.sort(key=lambda item: item["id"])
    return singletons


def extract_dead_ids(
    broken_web: list[dict[str, Any]],
    broken_rus: list[dict[str, Any]],
) -> dict[str, list[int]]:
    return {
        "web": sorted({entry["id"] for entry in broken_web if isinstance(entry.get("id"), int)}),
        "rus": sorted({entry["id"] for entry in broken_rus if isinstance(entry.get("id"), int)}),
    }


def assert_invariants(
    pairs: list[dict[str, Any]],
    web_singletons: list[dict[str, Any]],
    rus_singletons: list[dict[str, Any]],
    resources: ResourceIndex,
) -> None:
    web_pair_ids: list[int] = [entry["web_id"] for entry in pairs]
    rus_pair_ids: list[int] = [entry["rus_id"] for entry in pairs]

    def first_duplicate(values: list[int]) -> int | None:
        seen: set[int] = set()
        for value in values:
            if value in seen:
                return value
            seen.add(value)
        return None

    duplicate_web = first_duplicate(web_pair_ids)
    if duplicate_web is not None:
        raise SystemExit(f"[fatal] duplicate web id in pairs: {duplicate_web}")

    duplicate_rus = first_duplicate(rus_pair_ids)
    if duplicate_rus is not None:
        raise SystemExit(f"[fatal] duplicate rus id in pairs: {duplicate_rus}")

    web_pair_set = set(web_pair_ids)
    rus_pair_set = set(rus_pair_ids)
    web_singleton_set = {entry["id"] for entry in web_singletons}
    rus_singleton_set = {entry["id"] for entry in rus_singletons}

    web_overlap = web_pair_set & web_singleton_set
    if web_overlap:
        raise SystemExit(f"[fatal] web ids appear in both pairs and singletons: {sorted(web_overlap)}")
    rus_overlap = rus_pair_set & rus_singleton_set
    if rus_overlap:
        raise SystemExit(f"[fatal] rus ids appear in both pairs and singletons: {sorted(rus_overlap)}")

    web_unknown = (web_pair_set | web_singleton_set) - resources.web_ids
    if web_unknown:
        raise SystemExit(f"[fatal] web ids not in transformed_resources.json: {sorted(web_unknown)}")
    rus_unknown = (rus_pair_set | rus_singleton_set) - resources.rus_ids
    if rus_unknown:
        raise SystemExit(f"[fatal] rus ids not in transformed_resources.json: {sorted(rus_unknown)}")

    web_uncovered = resources.web_ids - web_pair_set - web_singleton_set
    if web_uncovered:
        raise SystemExit(
            f"[fatal] web ids missing from the normalization table: {sorted(web_uncovered)}"
        )
    rus_uncovered = resources.rus_ids - rus_pair_set - rus_singleton_set
    if rus_uncovered:
        raise SystemExit(
            f"[fatal] rus ids missing from the normalization table: {sorted(rus_uncovered)}"
        )


def compute_audit_version(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(64 * 1024), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def build_normalization(
    audit_path: Path,
    reviews_path: Path,
    resources_path: Path,
) -> dict[str, Any]:
    audit = load_json(audit_path)
    reviews = validate_reviews_shape(load_yaml(reviews_path))
    resources = build_resource_index(load_json(resources_path))

    buckets = collect_audit_buckets(audit)

    strict_pairs = [
        {"web_id": entry["web"], "rus_id": entry["rus"], "source": "strict"}
        for entry in buckets["strict_pairs"]
    ]
    auto_pairs = build_auto_pairs(buckets["web_auto"], buckets["rus_auto"])
    manual_pairs = build_manual_pairs(
        reviews["pairs"], buckets["web_review"], buckets["rus_review"]
    )
    pairs = strict_pairs + auto_pairs + manual_pairs

    web_singletons = build_singletons(
        reviews["web_singletons"], buckets["web_unlocalized"], "web"
    )
    rus_singletons = build_singletons(
        reviews["rus_singletons"], buckets["rus_unlocalized"], "rus"
    )

    assert_invariants(pairs, web_singletons, rus_singletons, resources)

    dead_ids = extract_dead_ids(buckets["broken_web"], buckets["broken_rus"])
    dead_total = len(dead_ids["web"]) + len(dead_ids["rus"])

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": audit_path.name,
        "audit_version": compute_audit_version(audit_path),
        "summary": {
            "pairs": len(pairs),
            "strict_pairs": len(strict_pairs),
            "auto_pairs": len(auto_pairs),
            "manual_pairs": len(manual_pairs),
            "web_singletons": len(web_singletons),
            "rus_singletons": len(rus_singletons),
            "dead_babel_ignored": dead_total,
        },
        "pairs": pairs,
        "web_singletons": web_singletons,
        "rus_singletons": rus_singletons,
        "dead_babel_ignored": dead_ids,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build babel_normalization.json from audit + reviews.",
    )
    parser.add_argument("--audit", type=Path, default=AUDIT_PATH)
    parser.add_argument("--reviews", type=Path, default=REVIEWS_PATH)
    parser.add_argument("--resources", type=Path, default=RESOURCES_PATH)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = build_normalization(args.audit, args.reviews, args.resources)

    with args.output.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")

    summary = payload["summary"]
    print(f"[ok] wrote {args.output.relative_to(ROOT)}")
    print(
        f"     pairs={summary['pairs']} "
        f"(strict={summary['strict_pairs']}, auto={summary['auto_pairs']}, "
        f"manual={summary['manual_pairs']})"
    )
    print(
        f"     web_singletons={summary['web_singletons']} "
        f"rus_singletons={summary['rus_singletons']} "
        f"dead_babel_ignored={summary['dead_babel_ignored']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
